name: mobile_team_ui_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/e_commerce_app/e_commerce_app_home.PNG
    - assets/images/design_course/design_course_app_home.png
    - assets/images/fitness_app/fitness_app_home.png
    - assets/images/food_app/food_app.png
    - assets/images/hotel/hotel_app_home.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto_Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto_Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: WorkSans-Bold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: WorkSans-Bold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: WorkSans-Medium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf
    - family: WorkSans-Regular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: WorkSans-SemiBold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf
